# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d96d5abf36b3e35783dd9df98b6d07d9af56faa7d99c514754d8e9a70481d643b0d83b00e14d9d8cca19f01baeb22f19a9b48ce3735e4a1a6669c90c83516b48

test:
  secret_key_base: 1a8986633e9637292daa34436558433462445824cfcbfb83ce40beaa04b48e569a0da6c977957fa4a52f7e1607dab851a8de4273e44a981badae9f095115c871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
